### PR TITLE
Swift 3 migration

### PR DESCRIPTION
**Pull request by diegomarcon**

### CODE REVIEW

**Comment by mrtj** [comment]
Thank you for the excellent work, I look forward this PR to be accepted

**Comment by mrtj** [comment]
Hi, I think I found the bug why the result of the login does not arrive to the view controller in this PR. In `LoginViewController.bindEvents()` calling `dispose()` directly on the signal causes the observers to be disposed immediately. If you change theses `dispose()` calls to `dispose(in: disposeBag)` calls similar as for `loginTaps` in `LoginViewModel` then the observer code will be executed as expected.

**Comment by mrtj** [comment]
I created PR #2  to the swift-3-migration branch with the fix above.

**Comment by diegomarcon** [comment]
@mrtj First of all thank you reviewing this PR and for contributing to this sample. 
I'll review everything as soon as possible, merge and update the medium post about it :)

**Pull request merged**
